<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\Admin.SharedKernel.ValueObjects\Admin.SharedKernel.ValueObjects.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Admin.SharedKernel.ValueObjects" />
    <Using Include="ServicesService.Domain.Common" />
    <Using Include="ServicesService.Domain.ValueObjects" />
  </ItemGroup>

</Project>
