using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ServicesService.Domain.Entities;

namespace ServicesService.Infrastructure.Persistence.Configurations;

public class ServiceConfiguration : IEntityTypeConfiguration<Service>
{
    public void Configure(EntityTypeBuilder<Service> builder)
    {
        builder.ToTable("Services");
        builder.HasKey(s => s.Id);
        builder.HasAlternateKey(s => new { s.TenantId, s.Id });

        builder.Property(s => s.TenantId).IsRequired();
        builder.Property(s => s.Code).IsRequired();
        builder.Property(s => s.Name).IsRequired().HasMaxLength(Service.NameMaxLength);
        builder.Property(s => s.Description).HasMaxLength(Service.DescriptionMaxLength);
        builder.Property(s => s.DurationMinutes).IsRequired();
        builder.Property(s => s.MinDurationMinutes).IsRequired();
        builder.Property(s => s.MaxDurationMinutes).IsRequired();
        builder.Property(s => s.Price).IsRequired().HasPrecision(10, 2);
        builder.Property(s => s.MaxDiscountPercentage).IsRequired().HasPrecision(5, 2);
        builder.Property(s => s.CategoryId);
        builder.HasOne<Category>()
            .WithMany()
            .HasForeignKey(s => new { s.TenantId, s.CategoryId })
            .HasPrincipalKey(c => new { c.TenantId, c.Id })
            .OnDelete(DeleteBehavior.Restrict);

        // Case-insensitive uniqueness enforced by the database itself,
        // not just the application-level NameExistsAsync pre-check: a generated,
        // always-lowercase shadow column backs the unique index so two concurrent
        // requests can't both persist "Corte"/"corte". Filtered to non-deleted rows so
        // a soft-deleted service doesn't block reusing its name.
        builder.Property<string>("NameNormalized").HasComputedColumnSql("lower(\"Name\")", stored: true);
        builder.HasIndex("TenantId", "NameNormalized")
            .IsUnique()
            .HasFilter("\"DeletedAt\" IS NULL");

        // Code is system-generated by IServiceCodeGenerator, unique per tenant.
        builder.HasIndex(s => new { s.TenantId, s.Code })
            .IsUnique()
            .HasFilter("\"DeletedAt\" IS NULL");

        builder.HasMany(s => s.Tags)
            .WithMany()
            .UsingEntity<Dictionary<string, object>>(
                "ServiceTags",
                tag => tag.HasOne<Tag>()
                    .WithMany()
                    .HasForeignKey("TenantId", "TagsId")
                    .HasPrincipalKey(nameof(Tag.TenantId), nameof(Tag.Id))
                    .OnDelete(DeleteBehavior.Cascade),
                service => service.HasOne<Service>()
                    .WithMany()
                    .HasForeignKey("TenantId", "ServiceId")
                    .HasPrincipalKey(nameof(Service.TenantId), nameof(Service.Id))
                    .OnDelete(DeleteBehavior.Cascade),
                join =>
                {
                    join.ToTable("ServiceTags", "services");
                    join.Property<Guid>("TenantId").IsRequired();
                    join.HasKey("TenantId", "ServiceId", "TagsId");
                });

        builder.Metadata.FindSkipNavigation(nameof(Service.Tags))!
            .SetPropertyAccessMode(PropertyAccessMode.Field);
    }
}
